name: "nixos-module-tests"
on:
  pull_request:
  push:
jobs:
  nix:
    runs-on: ubuntu-latest
    name: Run NixOS module tests
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
    - name: Run flake checks
      run: nix flake check -L
